#!/usr/bin/env node

const UDP_PORT = 5680;

const WS_HOST = '127.0.0.1';
const WS_PORT = 3100;

const WebSocket = require('uws');
const dgram = require('dgram');

var WebSocketServer = WebSocket.Server;
var wss = new WebSocketServer({ port: WS_PORT });

var server = dgram.createSocket('udp4');

server.on('message', function (message, remote) {
    msg = message.toString()
    
    wss.clients.forEach(function each(client) {
      if (client !== wss && client.readyState === WebSocket.OPEN) {
        client.send(msg);
      }
    });
});

server.bind(UDP_PORT, '127.0.0.1');
